7 allow initial prompt to be a configuration not hardcoded
open-build/BabbleBeaver- pull request #18
Opened 2024-06-27 17:58 UTC by SXV357

2024-06-30 16:40 UTC, lxy009 requested changes
Could you help me understand what the `chatbot.db` file is?
@SXV357 and @kalexander - is this specific to ollama? and is it necessary to include in the codebase?

2024-07-01 19:54 UTC, lxy009 approved these changes

2024-07-01 19:57 UTC, lxy009 approved these changes

2024-07-01 19:57 UTC, merged

2024-07-02 17:37 UTC, kalexander commented
> Could you help me understand what the `chatbot.db` file is? @SXV357 and @kalexander - is this specific to ollama? and is it necessary to include in the codebase?

chatbot.db is a database file for sqllite.. it is a table just showing the messages across babble beaver.. see the message_logger.py module

2024-07-02 17:39 UTC, glind commented
> Could you help me understand what the `chatbot.db` file is? @SXV357 and @kalexander - is this specific to ollama? and is it necessary to include in the codebase?

I think this is just the sqlite DB that was checked in, it should probably be in .gitignore becasue it's not needed outside of development and testing.